version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
