[tools]
node = "22"
pnpm = "latest"

[tasks.install_deps]
run = "pnpm install"
description = "Instal·la les dependències del projecte"

[tasks.lint]
run = "pnpm run lint"
depends = "install_deps"
description = "Comprova l'estil del codi"

[tasks.dev]
run = "pnpm run dev"
depends = "install_deps"
description = "Executa el projecte per desenvolupar-lo"

[tasks.build]
run = "pnpm run build"
depends = "install_deps"
description = "Genera els fitxers per publicar el projecte"
