[tools]
bun = "latest"

[tasks.install_deps]
run = "bun --bun install --frozen-lockfile"
description = "Instal·la les dependències del projecte"

[tasks.lint]
run = "bun --bun run lint"
depends = "install_deps"
description = "Comprova l'estil del codi"

[tasks.dev]
run = "bun --bun run dev"
depends = "install_deps"
description = "Executa el projecte per desenvolupar-lo"

[tasks.build]
run = "bun --bun run build"
depends = "install_deps"
description = "Genera els fitxers per publicar el projecte"
