name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Cache pnpm-installed packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.json') }}

      - run: mise run lint
