name: Setup
description: "Setup mise and caching for bun and Next.js"

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v2

    - name: Cache for bun-installed packages
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - name: Cache for Next
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.mjs', '**.css', 'data/*', 'public/*') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
